### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/hts_engine_API#10]
I am trying to install hts_engine_API for Japanese synthesis.
I ran command: `./waf configure && ./waf build install`
Configure happens without any problem. But while installing this occurs:

`Build failed`
Traceback (most recent call last):
  File "/home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/hts_engine_API/src/.waf3-2.0.19-35d7801c914ed8b2e0239b010d034f89/waflib/Build.py", line 596, in do_install
    self.copy_fun(src,tgt)
  File "/home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/hts_engine_API/src/.waf3-2.0.19-35d7801c914ed8b2e0239b010d034f89/waflib/Build.py", line 539, in copy_fun
    shutil.copy2(src,tgt)
  File "/home/yasin/espnet/tools/venv/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/yasin/espnet/tools/venv/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
`PermissionError: [Errno 13] Permission denied: '/usr/local/include/HTS_hidden.h'`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/hts_engine_API/src/.waf3-2.0.19-35d7801c914ed8b2e0239b010d034f89/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/hts_engine_API/src/.waf3-2.0.19-35d7801c914ed8b2e0239b010d034f89/waflib/Build.py", line 562, in run
    fun(x.abspath(),y.abspath(),x.path_from(launch_node))
  File "/home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/hts_engine_API/src/.waf3-2.0.19-35d7801c914ed8b2e0239b010d034f89/waflib/Build.py", line 602, in do_install
    `raise Errors.WafError('Could not install the file %r'%tgt,e)`
`waflib.Errors.WafError: Could not install the file '/usr/local/include/HTS_hidden.h'`

Why is this happening?

**Comment by Arafat4341** [comment]
Solved it with adding sudo before ./waf.
