### ISSUE TITLE
Instllation issue on Python3.7

### ISSUE THREAD

**Issue by kamo-naoyuki** [r9y9/hts_engine_API#6]
I don't know almost anything about waf, but possibly now the installation from waf is failed with python3.7?

I got the following error with python3.7.3

```
Traceback (most recent call last):
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Node.py", line 281, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/data/work/hts_engine_API/src/wscript", line 21, in options
    opt.load('compiler_c')
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Context.py", line 90, in load
    fun(self)
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Node.py", line 330, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/data/work/hts_engine_API/src/.waf3-1.8.16-d4654a3b52cf852de89d1b4f6194b833/waflib/Node.py", line 330, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

I successfully installed with latest waf. Thanks.

**Comment by r9y9** [comment]
Thank you for the report. This should be fixed now.
